---
/**/controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster
    drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

/**/imu_broadcaster:
  ros__parameters:
    tf_frame_prefix_enable: false
    sensor_name: <namespace>/imu
    frame_id: imu_link
    static_covariance_orientation: [1.9e-3, 0.0, 0.0, 0.0, 1.9e-3, 0.0, 0.0, 0.0, 1.9e-3] # Values taken from datasheet
    static_covariance_angular_velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0e-3] # Values measured experimentally
    static_covariance_linear_acceleration: [6.4e-2, 0.0, 0.0, 0.0, 2.2e-2, 0.0, 0.0, 0.0, 0.0] # Values measured experimentally

/**/drive_controller:
  ros__parameters:
    tf_frame_prefix_enable: false

    front_left_wheel_name: fl_wheel_joint
    front_right_wheel_name: fr_wheel_joint
    rear_left_wheel_name: rl_wheel_joint
    rear_right_wheel_name: rr_wheel_joint

    wheel_separation_x: 0.170
    wheel_separation_y: 0.270
    wheel_radius: 0.047

    wheel_separation_x_multiplier: 0.95  # Based on real measurements
    wheel_separation_y_multiplier: 0.95  # Based on real measurements

    wheel_radius_multiplier: 1.05  # Based on real measurements

    # Feedback from motors is published at around 20 Hz
    publish_rate: 25.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [3.3e-5, 3.3e-5, 0.0, 0.0, 0.0, 2.8e-3] # Values measured experimentally

    # Whether to use feedback or commands for odometry calculations
    open_loop: false

    # Update odometry from velocity
    # in sensor fusion only velocity is used and with this setting it is more accurate
    position_feedback: false
    # velocity computation filtering
    velocity_rolling_window_size: 1

    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true

    # Velocity and acceleration limits
    linear:
      x:
        max_velocity: 1.0 # m/s
        min_velocity: -1.0 # m/s
        max_acceleration: 0.75 # m/s^2
        max_deceleration: -0.75 # m/s^2
        max_acceleration_reverse: -0.75 # m/s^2
        max_deceleration_reverse: 0.75 # m/s^2
        max_jerk: .nan # m/s^3
        min_jerk: .nan # m/s^3

      y:
        max_velocity: 1.0 # m/s
        min_velocity: -1.0 # m/s
        max_acceleration: 0.75 # m/s^2
        max_deceleration: -0.75 # m/s^2
        max_acceleration_reverse: -0.75 # m/s^2
        max_deceleration_reverse: 0.75 # m/s^2
        max_jerk: .nan # m/s^3
        min_jerk: .nan # m/s^3

    angular:
      z:
        max_velocity: 3.14 # rad/s
        min_velocity: -3.14 # rad/s
        max_acceleration: 3.0 # rad/s^2
        max_deceleration: -3.0 # rad/s^2
        max_acceleration_reverse: -3.0 # rad/s^2
        max_deceleration_reverse: 3.0 # rad/s^2
        max_jerk: .nan # rad/s^3
        min_jerk: .nan # rad/s^3
