---
components:
  - type: LDR02
    parent_link: cover_link
    xyz: 0.02 0.0 0.0
    rpy: 0.0 0.0 0.0

  - type: CAM11
    parent_link: camera_mount_link
    xyz: -0.01 0.0 0.02
    rpy: 0.0 0.0 0.0
